import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property<string> current_dir: "/";
    callback set-current-dir();
    VerticalBox {
        Text {
            text: "Current directory: \{root.current_dir}";
        }
        /* Button {
            text: "a button";
            clicked => {
                root.set-current-dir();
            }
        } */
    }
}
