import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property<string> current_dir: "loading...";
    callback set-current-dir();
    callback open-folder();
    VerticalBox {
        Text {
            text: "Current directory: \{root.current_dir}";
        }
        Button {
            text: "Open a folder";
            clicked => {
                root.open-folder();
            }
        }
    }
}
